### ISSUE TITLE
Problem building GROMACS-2021-fosscuda-2020b.eb on CentOS 8.3

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyconfigs#12673]
Hi,

I'm having a problem building GROMACS-2021-fosscuda-2020b.eb on CentOS 8.3 (Cascade Lake, RTX6000). I *think* the build is failing during the pytest for gmxapi but I might be mis-reading the log. Any help would be appreciated, the build log can be found at https://gist.github.com/dithwick/4c4f30facf409c816259ee364f547299

Thanks

**Comment by dithwick** [comment]
I've updated the gist with --parallel=1. I've also added the output from running --trace

**Comment by dithwick** [comment]
I've just tested the easybuild with the python components commented out and it builds fine e.g.
```
name = 'GROMACS'
version = '2021'

homepage = 'https://www.gromacs.org'
description = """
GROMACS is a versatile package to perform molecular dynamics, i.e. simulate the
Newtonian equations of motion for systems with hundreds to millions of
particles.

This is a GPU enabled build, containing both MPI and threadMPI builds.

It also contains the gmxapi extension for the single precision MPI build.
"""

toolchain = {'name': 'fosscuda', 'version': '2020b'}
toolchainopts = {'openmp': True, 'usempi': True}

source_urls = [
    'https://ftp.gromacs.org/pub/gromacs/',
    'ftp://ftp.gromacs.org/pub/gromacs/',
]
sources = [SOURCELOWER_TAR_GZ]
patches = [
    'GROMACS-2019_fix_omp_num_threads_and_google_test_death_style_in_tests.patch',
    'GROMACS-2019_increase_test_timeout_for_GPU.patch',
    'GROMACS-2021_fix_gmxapi_gmx_allowed_cmd_name.patch',
    'GROMACS-2020.5_fix_threads_gpu_Gmxapitests.patch',
]
checksums = [
    'efa78ab8409b0f5bf0fbca174fb8fbcf012815326b5c71a9d7c385cde9a8f87b',  # gromacs-2021.tar.gz
    # GROMACS-2019_fix_omp_num_threads_and_google_test_death_style_in_tests.patch
    '406f5edd204be812f095a6f07ebc2673c5f6ddf1b1c1428fd336a80b9c629275',
    # GROMACS-2019_increase_test_timeout_for_GPU.patch
    '0d16f53d428155197a0ed0b0974ce03422f199d7c463c4a9156a3b99e3c86234',
    # GROMACS-2021_fix_gmxapi_gmx_allowed_cmd_name.patch
    'b7ffb292ec362e033db1bedd340353f0644dbaae872127750f3dda1ac7e87d49',
    # GROMACS-2020.5_fix_threads_gpu_Gmxapitests.patch
    '89fbb7e2754de45573632c74f53563bb979df9758c949238a35865391d6b53fb',
]

builddependencies = [
    ('CMake', '3.18.4'),
#    ('scikit-build', '0.11.1'),
]

#dependencies = [
#    ('Python', '3.8.6'),
#    ('SciPy-bundle', '2020.11'),
#    ('networkx', '2.5'),
#]

#exts_defaultclass = 'PythonPackage'

#exts_default_options = {
#    'source_urls': [PYPI_SOURCE],
#    'use_pip': True,
#    'download_dep_fail': True,
#    'sanity_pip_check': True,
#}

#exts_list = [
#    ('gmxapi', '0.2.0', {
#        'preinstallopts': "export GMXTOOLCHAINDIR=%(installdir)s/share/cmake/gromacs_mpi && ",
#        'checksums': ['3954bf123da12fc60bcfaeed8263f5e2d3e16e5136c2bb5c8207b20fa7406788'],
#    }),
#]

#modextrapaths = {
#    'PYTHONPATH': 'lib/python%(pyshortver)s/site-packages',
#}

moduleclass = 'bio'

```
Just a thought but is it possible that there's a problem because we don't have a package installed providing `/usr/bin/python?` We only have `python3` at the moment.

**Comment by akesandgren** [comment]
No since it contained the Python dep it will use Python from that dep for everything, except driving EB itself.

**Comment by akesandgren** [comment]
Can you try with the deps in place, i.e. comment out only from exts_defaultclass and down ?

**Comment by dithwick** [comment]
> No since it contained the Python dep it will use Python from that dep for everything, except driving EB itself.

Which is what I was thinking. Except I've just used alternatives to update /usr/bin/python to point to /usr/bin/python3 (as per https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-python3_configuring-basic-system-settings) and it's now passed the first iteration and is onto the second (which is further than it had got to before). So something in the gromacs build wants /usr/bin/python to exist from the looks of it (hardcoded somewhere).

**Comment by akesandgren** [comment]
Ohhh, need to weed that one out then... will take a look.

**Comment by akesandgren** [comment]
Ah yes... plenty. Will create patch...

**Comment by dithwick** [comment]
@akesandgren That you :-)

**Comment by dithwick** [comment]
Well, it got most of the way through the build and then failed at the end:
```
== installing...
== taking care of extensions...
== installing extension gmxapi 0.2.0 (1/1)...
==      configuring...
==      building...
==      testing...
==      installing...
== restore after iterating...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/easybuild/GROMACS/2021/fosscuda-2020b): build failed (first 300 chars): Sanity check failed: extensions sanity check fai
led for 1 extensions: gmxapi
failing sanity check for 'gmxapi' extension: found one or more downloaded dependencies: Collecting install, found one or more downloaded dependencies: Collecting install (took 1 hour 2 min
 25 sec)
== Results of the build can be found in the log file(s) /tmp/eb-r5djvo9a/easybuild-GROMACS-2021-20210420.105904.NHZVx.log
ERROR: Build of /home/dugan/gitrepos/easybuild-repos/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS/GROMACS-2021-fosscuda-2020b.eb failed (err: "build failed (first 300 chars): Sani
ty check failed: extensions sanity check failed for 1 extensions: gmxapi\nfailing sanity check for 'gmxapi' extension: found one or more downloaded dependencies: Collecting install, found 
one or more downloaded dependencies: Collecting install")

```
I think that's the same error I was seeing with CentOS 7.9 (that's at least progress).

**Comment by akesandgren** [comment]
Yeah, have forgotten to fix the extension part to include "install"...

**Comment by akesandgren** [comment]
Odd. I see no reference to that when trying a rebuild...

**Comment by akesandgren** [comment]
Nor do I have /usr/bin/python in my container and it does not show the previous problem.
So there must be something else causing the problem here...

**Comment by akesandgren** [comment]
Did/do you have a /usr/bin/python2 ??

**Comment by dithwick** [comment]
Yes it's a symlink `/usr/bin/python2 -> python2.7`

**Comment by akesandgren** [comment]
trying without a /usr/bin/python2 but that doesn't cause problems either...

Something CentOS related, can't find any problems on Ubuntu at least

**Comment by dithwick** [comment]
Yep, it's really odd! Don't know if it makes a difference but this system has never been anything other than CentOS 8.3. That said I get the sanity check error on CentOS 7.9 as well.

**Comment by akesandgren** [comment]
Ha, for building the fosscuda (was jist trying foss version earlier) I do get that same "Collecting install".
At least now I have something to work with.

**Comment by dithwick** [comment]
Great! (well not great but I guess kinda good for me ;-) )

**Comment by akesandgren** [comment]
but gmxapi-0.2.0 doesn't show any signs of requiring the "install" pypi package.... so why is it getting downloaded in the first place?

**Comment by dithwick** [comment]
Is it possible that the gmxapi that comes with the gromacs tarball (under python_packaging/src) is somehow conflicting with that installed via pypi?

**Comment by akesandgren** [comment]
I think I managed to miss that it existed there in the first place.

**Comment by dithwick** [comment]
I *think* development of gmxapi moved into the main GROMACS repo and the changes are pulled every so often into https://github.com/kassonlab/gmxapi but I don't then know how the version on pypi relates to that provided in the gromacs tarball. I've no idea how you would change the easyconfig to use the version built from the tarball.

**Comment by akesandgren** [comment]
for GROMACS 2021 the code in the gromacs tar ball and the gmxapi-0.2.0 from pypi are identical at least.

I'll do some testbuilds to see what happens with vs without the explicit gmxapi extension

**Comment by akesandgren** [comment]
This might have something to do with it perhaps:
```
run.py:542 INFO cmd "export GMXTOOLCHAINDIR=/home/a/ake/Public/easybuild/software/GROMACS/2021-fosscuda-2020b/share/cmake/gromacs_mpi &&
 pip install --prefix=/home/a/ake/Public/easybuild/software/GROMACS/2021-fosscuda-2020b install  --verbose  --no-deps  --ignore-installed  --no-build-isolation  ."
```
Note the double "install"

**Comment by dithwick** [comment]
Ah, yeah that might be the problem!

**Comment by akesandgren** [comment]
I though I had gotten that part of gromacs.py correct but apparently not quite, debugging...

**Comment by akesandgren** [comment]
Try the new easyblock...

**Comment by dithwick** [comment]
I've had to temporarily change to another system (CentOS 7.9) that is showing the same sanity check error. To confirm, when I run:

`eb GROMACS-2021-fosscuda-2020b.eb -r`

It fails with

```
== taking care of extensions...
== installing extension gmxapi 0.2.0 (1/1)...
==      configuring...
==      building...
==      testing...
==      installing...
== restore after iterating...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/pfsxns/easybuild/GROMACS/2021/fosscuda-2020b): build failed (first 300 chars): Sanity check failed: extensions sanity check failed for 1 extensions: gmxapi
failing sanity check for 'gmxapi' extension: found one or more downloaded dependencies: Collecting install, found one or more downloaded dependencies: Collecting install (took 19 min 50 sec)
== Results of the build can be found in the log file(s) /tmp/eb-JzysB8/easybuild-GROMACS-2021-20210420.171803.BLCNb.log
ERROR: Build of /home/user/gitrepos/easybuild-repos/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS/GROMACS-2021-fosscuda-2020b.eb failed (err: "build failed (first 300 chars): Sanity check failed: extensions sanity check failed for 1 extensions: gmxa
pi\nfailing sanity check for 'gmxapi' extension: found one or more downloaded dependencies: Collecting install, found one or more downloaded dependencies: Collecting install")
```

but when I try the new easyblock:

`eb GROMACS-2021-fosscuda-2020b.eb -r --include-easyblocks-from-pr=2391`

It builds successfully:

```
== taking care of extensions...
== installing extension gmxapi 0.2.0 (1/1)...
==      configuring...
==      building...
==      testing...
==      installing...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 20 min 6 sec)
== Results of the build can be found in the log file(s) /home/user/.local/easybuild/desktop/2018/software/GROMACS/2021-fosscuda-2020b/easybuild/easybuild-GROMACS-2021-20210420.181814.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /tmp/eb-RU6E7w/easybuild-9VMUdy.log* have been removed.
== Temporary directory /tmp/eb-RU6E7w has been removed.

```

**Comment by smoors** [comment]
fixed via https://github.com/easybuilders/easybuild-easyblocks/pull/2391

**Comment by dithwick** [comment]
@smoors Sorry, there were two bugs covered by this issue, the original problem was that /usr/bin/python has been hard-coded in the gromacs source code so a patch needs creating RHEL8 no longer has a default for /usr/bin/python. Should I re-raise that as a new issue?

**Comment by smoors** [comment]
ah ok sorry about that

**Comment by dithwick** [comment]
No worries, it wasn't obvious.

**Comment by dithwick** [comment]
Hi @akesandgren . By any chance did you have any luck finding out why /usr/bin/python is needed for gmxapi_extension_pytest? I've been looking and I still can't work it out.

**Comment by akesandgren** [comment]
Haven't had time. Fighting with ANSYS on a !RH system...

**Comment by dithwick** [comment]
@akesandgren  No worries, completely understand. TBH it's going to save me pain in the long run just to point /usr/bin/python to /usr/bin/python3 so I might just do that.

**Comment by ocaisa** [comment]
I also ran into this problem on Rocky and can't figure out where exactly in the source code the issue is coming from.

**Comment by boegel** [comment]
I don't think this is still relevant, so closing...
